<a href="https://colab.research.google.com/github/AKASH4671/Anomaly-Detection-Using-Two-Stage-Autoencoders-on-Time-Series-Data/blob/main/Anomaly_for_one_sensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:

data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Final Project/part 2/data/PS6.txt', delimiter='\t')


In [ ]:
data

9.818  9.823  9.844  9.861  9.877  9.866  9.851  9.833  9.817  9.824  \
0     9.592  9.573  9.578  9.586  9.604  9.622  9.625  9.620  9.604  9.585   
1     9.505  9.484  9.476  9.480  9.493  9.513  9.523  9.526  9.509  9.491   
2     9.422  9.415  9.394  9.378  9.370  9.377  9.399  9.411  9.425  9.422   
3     9.315  9.296  9.287  9.280  9.288  9.307  9.325  9.336  9.325  9.312   
4     9.250  9.264  9.278  9.270  9.253  9.236  9.219  9.226  9.238  9.257   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
2199  9.839  9.840  9.848  9.868  9.894  9.893  9.883  9.861  9.842  9.836   
2200  9.837  9.827  9.816  9.833  9.856  9.877  9.885  9.873  9.866  9.848   
2201  9.856  9.873  9.873  9.866  9.846  9.832  9.827  9.831  9.851  9.866   
2202  9.858  9.840  9.828  9.817  9.826  9.842  9.861  9.877  9.865  9.849   
2203  9.849  9.870  9.887  9.886  9.878  9.856  9.840  9.833  9.840  9.859   

      ...  9.616.29  9.594.22  9.58.16  9.571.9  9.576.6  9.599.20  9.62.28  \
0     ...     9.530     9.514    9.495    9.482    9.474     9.487    9.502   
1     ...     9.412     9.425    9.414    9.398    9.384     9.368    9.373   
2     ...     9.332     9.321    9.309    9.292    9.278     9.280    9.287   
3     ...     9.226     9.238    9.260    9.277    9.276     9.267    9.247   
4     ...     9.175     9.191    9.203    9.200    9.184     9.170    9.153   
...   ...       ...       ...      ...      ...      ...       ...      ...   
2199  ...     9.860     9.854    9.833    9.825    9.824     9.834    9.859   
2200  ...     9.823     9.842    9.855    9.866    9.865     9.859    9.843   
2201  ...     9.873     9.866    9.855    9.830    9.819     9.821    9.832   
2202  ...     9.822     9.831    9.851    9.866    9.882     9.877    9.868   
2203  ...     9.868     9.846    9.837    9.838    9.848     9.870    9.882   

      9.639.39  9.634.39  9.615.48  
0        9.519     9.526     9.517  
1        9.382     9.402     9.423  
2        9.308     9.320     9.325  
3        9.233     9.224     9.231  
4        9.156     9.164     9.176  
...        ...       ...       ...  
2199     9.871     9.873     9.854  
2200     9.827     9.831     9.837  
2201     9.856     9.866     9.870  
2202     9.851     9.836     9.842  
2203     9.886     9.870     9.854  

[2204 rows x 6000 columns]

In [ ]:
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

In [ ]:
data_scaled

array([[0.92513079, 0.89014339, 0.89834418, ..., 0.79158095, 0.80502459,
        0.78866458],
       [0.76692378, 0.72836407, 0.71299774, ..., 0.5425216 , 0.57954144,
        0.61773328],
       [0.61599066, 0.60293965, 0.56399375, ..., 0.40799319, 0.43043161,
        0.43952831],
       ...,
       [1.40520722, 1.43546695, 1.43439514, ..., 1.4042306 , 1.42328485,
        1.43056616],
       [1.40884417, 1.37548136, 1.35262466, ..., 1.39514084, 1.36873248,
        1.37965045],
       [1.39247792, 1.43001372, 1.45983485, ..., 1.45876914, 1.4305585 ,
        1.40147147]])

In [ ]:
train_size = int(len(data) * 0.8)
train_data = data_scaled[:train_size]
test_data = data_scaled[train_size:]


In [ ]:

# first stage autoencoder
input_dim = train_data.shape[1]
input_layer = Input(shape=(input_dim,))
encoded = Dense(64, activation='relu')(input_layer)
encoded = Dense(32, activation='relu')(encoded)
decoded = Dense(64, activation='relu')(encoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder1 = Model(input_layer, decoded)
autoencoder1.compile(optimizer='adam', loss='mse')

# Train 1st stage
autoencoder1.fit(train_data, train_data, epochs=50, batch_size=32, shuffle=True)

# output
stage1_output = autoencoder1.predict(test_data)

Epoch 1/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.3947
Epoch 2/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0033
Epoch 3/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0038
Epoch 4/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0016
Epoch 5/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0017
Epoch 6/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0020
Epoch 7/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0021
Epoch 8/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0016
Epoch 9/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0021
Epoch 10/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022
Epoch 11/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0018
Epoch 12/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022
Epoch 13/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0017
Epoch 14/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0015
Epoch 15/50
56/56 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0014
Epoc

In [ ]:
# second stage autoencoder
input_layer2 = Input(shape=(input_dim,))
encoded2 = Dense(64, activation='relu')(input_layer2)
encoded2 = Dense(32, activation='relu')(encoded2)
decoded2 = Dense(64, activation='relu')(encoded2)
decoded2 = Dense(input_dim, activation='linear')(decoded2)

autoencoder2 = Model(input_layer2, decoded2)
autoencoder2.compile(optimizer='adam', loss='mse')

# Train 2nd stage
residual_data = test_data - stage1_output
autoencoder2.fit(residual_data, residual_data, epochs=50, batch_size=32, shuffle=True)

# output
stage2_output = autoencoder2.predict(residual_data)

Epoch 1/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0015
Epoch 2/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 3/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 4/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3346e-04
Epoch 5/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.5209e-04
Epoch 6/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9761e-04
Epoch 7/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3763e-04
Epoch 8/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.1827e-04
Epoch 9/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.9951e-04
Epoch 10/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.7887e-04
Epoch 11/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.5826e-04
Epoch 12/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.4449e-04
Epoch 13/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.3526e-04
Epoch 14/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.3355e-04
Epoch 15/50
14/14 ━━━━━━━━━

In [ ]:
# Combine the outputs of both stages
combined_output = stage1_output + stage2_output

In [ ]:
final = test_data - combined_output

In [ ]:
#Flatten the array to find the 90th percentile
flattened = final.flatten()
threshold = np.percentile(flattened, 95)

In [ ]:
anomalies = final > threshold

In [ ]:
anomaly_indices = np.where(anomalies)[0]
anomaly_indices.shape

(132300,)

In [ ]:
normal_points = final <= threshold

In [ ]:
a = np.where(normal_points)

In [ ]:
a.shape

(array([  0,   0,   0, ..., 440, 440, 440]),
 array([   0,    1,    2, ..., 5997, 5998, 5999]))

In [ ]:
plt.figure(figsize=(10, 6))

# Create masks for anomalies and normal points
anomalies = final > threshold
normal_points = final <= threshold

# Plot normal points
plt.scatter(np.where(normal_points)[1], np.where(normal_points)[0], color='blue', s=1, label='Normal')

# Plot anomalies
plt.scatter(np.where(anomalies)[1], np.where(anomalies)[0], color='red', s=1, label='Anomaly')

plt.title('Array Plot with Anomalies Highlighted')
plt.xlabel('Index')
plt.ylabel('Index')
plt.legend()
plt.show()